# Generated by Django 4.2.1 on 2023-12-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('shipping', models.FloatField(default=0)),
                ('img_path', models.CharField(max_length=100)),
            ],
        ),
    ]
